nmattia/niv

Main.hs, README.md
"NixOS/nixpkgs-channel" does not actually exist, the correct repo would be "NixOS/nixpkgs-channels"
=> Fix README spelling/name error

Main.hs, README.md
The added `--fetcher` option permits to set the nix fetcher used at evaluation time. It can be either `fetchurl` or `fetchTarball`.
If not set, the value is inferred from the suffix of the `url`: if the `url` ends with `tar.gz`, the `fetcher` is `fetchTarball`, `fetchurl` otherwise.
=> Add `fetcher` options

Main.hs, README.md
When the Nix restricted evaluation mode is enable, `builtins.fetch*`
functions can no longer be used. So, instead of using `builtins`
fetchers, we use fetchers from nixpkgs.
Note Hydra enables the restricted evaluation mode by default.
=> Support restricted evaluation mode

.circleci/config.yml
Right now warming up and saving the cache takes more time than the build
itself.
=> Drop the cache

src/Niv/Cli.hs, tests/expected/niv-init.json
Turns out that not storing the `null` values is a problem as `niv` will always try to re-download the attributes.
CC @michaelpj
=> Don't drop nulls

script/test
This will allow us to fetch binaries from cache.nixos.org without the dreaded
```
warning: unable to download 'https://cache.nixos.org/nix-cache-info': 
SSL peer certificate or SSH remote key was not OK (60)
```
error message.
=> Keep the nix ssl cert file variable when running the tests

.circleci/config.yml, default.nix
Adds completions for shells using the nixpkgs lib functions, and turns off profiling for our libraries and executables to speed up building.
=> Add completions and disable profiling

src/Niv/GitHub.hs, tests/default.nix
it fixes the issue with rate limiting in certain environments (like ZuriHac ;) )
=> GITHUB_TOKEN env variable support for github fetcher

default.nix
... which should not be global, because of nix - say no more
=> Fixing the build on darwin by adding those magical ghc flags to clear the global db

README.md, README.tpl.md, package.yaml, script/gen, src/Niv/Cli.hs, src/Niv/GitHub.hs, src/Niv/Logger.hs, tests/default.nix
Fixes #122 
Fixes #105 
Fixes #56
This drops the [github](https://github.com/phadej/github) library in favor of custom functions. This also adds some configuration through environment variables:
* `GITHUB_HOST`
* `GITHUB_API_HOST`
* `GITHUB_API_PORT`
* `GITHUB_PATH`
* `GITHUB_SECURE`
See `README` for more info.
@jfroche does the following work?
> $ niv add terraform-providers/terraform-provider-vault                                                                       
@nlewo I tweaked the tests a bit because I'm using different API calls. Now that we have some configuration I also dropped `nivForTest`.
Bonus: `niv`'s been marked as `broken` in nixpkgs for a while because of the dependency on the `github` library. Not anymore!
=> Use custom GitHub client

CHANGELOG.md, README.md, package.yaml
* Experimental support for `add` subcommands, in particular `niv add git`
* Various error message fixes
=> Release 0.2.4

CHANGELOG.md, README.md, nix/sources.nix, package.yaml, src/Data/Text/Extended.hs, src/Niv/Cli.hs, src/Niv/Logger.hs, src/Niv/Sources.hs
Closes #148 
Closes #134 
Closes #102 
To try this out, run
```
$ nix-env -iA niv -f https://github.com/nmattia/niv/tarball/nm-configure-sources
```
Closing #148 because the path to nix/sources.json is now configurable both on the CLI and from nix/sources.nix.
Closing #134 because technically sources.nix is now configurable, we'll need to create more specific tickets for particular configurations.
Closing #102 as well, although I suspect that `niv init` will create some funky sources.nix referencing a sources.json that's not the one provided by the user. @masaeedu can you confirm?
=> Allow custom location for nix/sources.json

CHANGELOG.md, README.md, nix/sources.nix, src/Niv/Cli.hs
See https://github.com/nmattia/niv/pull/159#issuecomment-563002902.  I opted to rename the option rather than updating the docs because the cli option is `--sources-json` and so using an option `sourcesJson` is more obvious than keeping it as `sourcesFile`.
=> Rename sourcesFile to sourcesJson

default.nix
This reduces the closure size by about 2G
Closes #178 
@novoxudonoser thanks for bringing this up!
=> Only build static executable in top-level niv attribute

nix/sources.nix, src/Niv/Sources.hs
This changes the logic to make sure the first `if` branch -- which pulls nixpkgs from sources.json -- is evaluated first. Moreover the `<nixpkgs>` check is changed to avoid actually evaluating `<nixpkgs>`.
Closes #143
=> Don't needlessly evaluate <nixpkgs>

default.nix, package.yaml, script/test
This moves the tests into a `tests` section of the `package.yaml`. Otherwise, the `niv-test` is shipped with the actual executable.
Closes #182
=> Remove the niv-test executable

default.nix, foo/default.nix, package.yaml
Closes #204 
The `callCabal2nix` invocation caused `cabal2nix` to be downloaded on
every install of `niv`. This introduces `foo`, a Nix function that does
exactly the same.
=> Get rid of cabal2nix

foo/default.nix
The `overrideCabal` mechanism, used to provide static executables, requires the `mkDerivation` argument in `callPackage` to be actually used. `foo/default.nix` currently ignores this argument, so this broke the static executable override.
=> Fix foo to get back static executable

nix/sources.nix, src/Niv/Sources.hs
The derivation name for package `foo` of type `tarball` is now `foo-src`
as opposed to `source`.
Closes #211
=> Prettify the derivation name in tarballs

README.md, src/Niv/Cli.hs, tests/github/default.nix
This adds a few configuration options to `niv init`:
* `--no-nixpkgs`: skips the import of nixpkgs
* `--nixpkgs-branch`: specifies the branch to use for nixpkgs
* `--nixpkgs`: specifies the repo to use for nixpkgs
=> Allow custom nixpkgs

README.md, README.tpl.md, examples/cpp-libosmium/nix/sources.json, src/Niv/Cli.hs, src/Niv/GitHub/Cmd.hs
Fixes https://github.com/nmattia/niv/issues/168
This is a completely naive search-and-replace with some artisanal description updating sprinkled on top. nixpkgs mirrors all the way down to 18.09, so I _think_ this is sufficient(?)
I've run the tests via `repl > :main` -- is there anything else I should do to verify?
=> Replace NixOS/nixpkgs-channels with NixOS/nixpkgs

README.md, src/Niv/Cli.hs, src/Niv/GitHub/Cmd.hs
The `niv` executable will now import `release-20.03` by default, as opposed to `release-19.09`. 
Fixes #233
=> Move to nixpkgs 20.03

README.md, README.tpl.md
Now that niv is part of nixpkgs, the installation is much simpler.
=> Update installation instructions

README.md, README.tpl.md, default.nix, nix/sources.nix, src/Niv/Sources.hs, tests/eval/default.nix
This updates the sources.nix to replace the `outPath` field of package
`foo` with the content of envionment variable `NIV_OVERRIDE_foo`. In the
environment variable name, all characters outside of `[a-zA-Z0-9_]` are
escaped to `_`.
=> Add NIV_OVERRIDE_{...}

nix/sources.nix, src/Niv/Sources.hs, tests/eval/default.nix
The file can now be imported even if there is no sources.json in the
same directory.
=> Make sources.nix remote friendly

nix/sources.nix, src/Niv/Sources.hs, tests/eval/default.nix
The `file` sources didn't get a name, and didn't get their name sanitized. This also fixes a
bug where builtins_fetchTarball would fail if because no name was given.
Fixes #264 
Fixes #262
=> Sanitize source name

nix/sources.nix, src/Niv/Cli.hs, src/Niv/Cmd.hs, src/Niv/Git/Cmd.hs, src/Niv/Git/Test.hs, src/Niv/GitHub/Cmd.hs, src/Niv/Local/Cmd.hs, src/Niv/Logger.hs, src/Niv/Sources.hs, tests/git/default.nix
Instead, sources now record either `branch` or `tag`. The fetcher
specifies the correct ref (`/refs/heads/...` or `/refs/tags/...`) which
works in the newest version of Nix. The `ref` attribute can still be set
to override the logic.
Fixes #266
=> Stop using ref in builtins.fetchGit fetcher

CHANGELOG.md, README.md, README.tpl.md, src/Niv/Cli.hs, src/Niv/GitHub/API.hs, tests/github/default.nix
Here we make sure that some environment variables are prepended
(GITHUB_PATH, GITHUB_INSECURE). For consistency's sake, other
environment variables (GITHUB_TOKEN, etc) _can_ also be prepended with
NIV_. This also issues a warning if `GITHUB_PATH` or `GITHUB_INSECURE`
is set.
=> Prepend environment variables with NIV_

nix/sources.nix, src/Niv/Sources.hs
Otherwise they're not accessible from the sandbox.
=> Turn NIV_OVERRIDE values into paths

CHANGELOG.md, README.md, README.tpl.md, src/Niv/GitHub.hs
Only guess the type of the download, if `-T` is not specified.
Respect `-T` if it is provided.
Closes #289 
Would be the behaviour I would have expected naively.
=> Respect type attribute

.github/actions/nix/install-nix, .github/workflows/test.yml
GitHub has deprecated setting the environment variables and paths via
echoing to the stdout:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Thus, this PR brings the code up to data with the recommendations in the
linked post. In short, paths are exposed to subsequent steps by
appending to the file named in `$GITHUB_PATH`, while environment
variables are set by appending `name=value` to the file named in
`$GITHUB_ENV`.
=> Fix GitHub action to publish to cachix

.github/workflows/test.yml
GitHub will soon change `ubuntu-latest` label to refer to Ubuntu 20.04:
https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/
Thus, to ensure `niv` will work there as well, this adds a matrix run on
ubuntu-20.04.
=> Start testing on Ubuntu 20.04

src/Niv/Update.hs
This refactoring makes the package build with both the currently
supported GHC (8.6.5) and newer ones (notably 8.10, I haven't tried with
8.8).
=> Slightly refactor renderTemplate to support newer GHCs

README.md, data/README.md, data/nixpkgs.json, src/Niv/Cli.hs, tests/git/default.nix, tests/github/default.nix
Closes #320 
This speeds up the `niv init` command by getting rid of
`nix-prefetch-url` calls (by default). In particular:
* `niv` itself is not added anymore
* `nixpkgs` is fetched from a "known" version
=> Speed up initialization

nix/sources.nix, src/Niv/Sources.hs
This change fixes the issue with sources.nix file that's been failing in
CI. The format was fixed by running `nixpkgs-fmt .` inside of the
nix-shell.
=> fix: formatting error in sources.nix

nix/sources.nix, src/Niv/Sources.hs
Referencing @awidegreen's PR https://github.com/nmattia/niv/pull/351, this one here does the same but also adds a warning if submodules are used but not supported by the user's nix version.
In that corner case, the user get's at least a warning trace on their shell that explains what's wrong here. Builds can still fail, but not silently without some hint on the reason.
=> Fetch submodules if supported, and warn if submodules are used but not supported

data/nixpkgs.json
For security reasons niv should not initialize with a potentially
outdated nixpkgs, that won't receive updates when even when the user
calls `niv update`.
Case in point: https://github.com/NixOS/nixpkgs/issues/227804#issuecomment-1519187006
=> Update the default nixpkgs to a rolling release

README.md, README.tpl.md
The readme.md does not reflect how niv current handles init, as it no longer follows the `release-xxx` branch, but instead unstable.
This might cause confusion for some, as they will try to use `release-xxx` branch, which shouldn't be used (AFAIK), but if one wants to pin to a stable branch `nixos-xxx` or `nixpkgs-xxx` should be used instead :)
=> updated readme from release-21.05 to nixos-unstable

default.nix, examples/cpp-libosmium/nix/sources.nix, examples/cpp-libosmium/overlay/libosmium.nix, nix/sources.nix, nix/termtosvg.nix, src/Niv/Sources.hs
This PR removes unnecessary usage of `rec`. This is not about `rec` sometimes considered an anti-pattern, this is about code, where this keyword can simply be removed. Because linters like [statix](https://github.com/nerdypepper/statix) complain, they have to configured to ignore `sources.nix`, which is somewhat annoying. This PR should fix that.
=> Remove Unnecessary Uses of `rec`

README.md, README.tpl.md
Just a small entry in the FAQ to explain how to use submodules with niv.
Its like very hard to find out how to do this correctly, because there is no example or doc about it. This PR tries to fix this.
=> Update FAQ to explain submodules

README.md, README.tpl.md
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org/
ref: https://github.com/NixOS/foundation/issues/113
=> README: update nixos link to official wiki

src/Niv/Cli.hs
closes https://github.com/nmattia/niv/issues/384
=> Add info when init with cached Nixpkgs

src/Niv/Cli.hs, src/Niv/Git/Cmd.hs, src/Niv/GitHub.hs, src/Niv/GitHub/API.hs, src/Niv/GitHub/Cmd.hs, src/Niv/Local/Cmd.hs, src/Niv/Logger.hs, src/Niv/Sources.hs, src/Niv/Update.hs, src/Niv/Update/Test.hs
I just ran hlint on the codebase and applied an automatic refactoring.
Feel free to drop any part of it.
=> hlint refactoring
