nmattia/niv

Main.hs, package.yaml
=> Update nix/sources.nix if necessary

app/Niv.hs, default.nix
=> Only generate nix/sources.json and nix/sources.nix

app/Niv.hs
Fixes #37 
@domenkozar  apologies for the delay. How does this look?
=> Warn if GitHub repository cannot be read

LICENSE, default.nix, package.yaml, script/upload
=> Prepare for release

default.nix, nix/sources.json
=> Use gitignore instead of duplicating it's logic

README.md, src/Niv/Cli.hs
Fixes #63.
At the moment this doesn't really give much informative output about what's happened, but I think we should fix this via https://github.com/nmattia/niv/issues/75.
=> Implement modify command

.gitignore
They were cluttering up my git status.
=> Add some more things to gitignore

src/Niv/Cli.hs, tests/expected/niv-init.json
This reduces diffs, which is always good!
=> Encode keys in sorted order

src/Niv/GitHub.hs
The call to get the last commit was missing, so it would hit rate limiting even
after the first call succeded.
=> Use GITHUB_TOKEN for all calls to the github api

nix/sources.json, src/Niv/GitHub.hs
... and fix compilation failure.
CC @basvandijk
=> nixpkgs: 18.09 -> 19.03

README.md, script/gen, src/Niv/Cli.hs
=> Allow show single package

src/Niv/Cli.hs, src/Niv/GitHub/Test.hs, src/Niv/Test.hs, src/Niv/Update.hs
=> Fix eager 'new' flagging

README.md, default.nix, package.yaml, src/Niv/Cli.hs
=> Show version in --help

nix/sources.nix, src/Niv/Cli.hs
=> Fix log and failure on `type = file` with recent nixpkgs

README.md, package.yaml
Forgot a PR when releasing 0.2.0
=> Release 0.2.1

default.nix, nix/default.nix, nix/sources.nix, tests/default.nix
Doing a bit a cleanup. Let me know what you think of the formatting changes.
=> Nixpkgs fmt

src/Niv/Cli.hs
The argument parsing for `niv add` was a bit ad-hoc. This makes it a bit
more principled by passing clearer types. Moreover the logic of argument
parsing is taking out of `cmdAdd`.
=> Refactor argument parsing

README.md, README.tpl.md, nix/sources.json, script/test, src/Niv/Cli.hs, src/Niv/GitHub/Cmd.hs, tests/github/default.nix, tests/github/expected/niv-init.json
I think 19.09 is stable enough to be the new default by now :)
=> init at 19.09

CHANGELOG.md, README.md, nix/sources.nix, package.yaml, script/gen, script/test, src/Niv/Sources.hs
=> Allow setting custom pkgs

README.md, README.tpl.md
=> Add README instructions for installing niv from nixpkgs

CHANGELOG.md
Closes https://github.com/nmattia/niv/issues/186
Thanks @ggreif!
=> Add CHANGELOG entry for 0.2.12

README.md, README.tpl.md, default.nix, src/Niv/Cli.hs
=> Mention the modify command in README

README.md, default.nix, src/Niv/Cli.hs, src/Niv/GitHub/Cmd.hs
Fixes https://github.com/nmattia/niv/issues/163
Fixes https://github.com/nmattia/niv/issues/98
Fixes https://github.com/nmattia/niv/issues/193
=> Clean up of a few issues

nix/sources.nix, src/Niv/Sources.hs
=> Retire builtin-tarball and builtin-url

src/Niv/GitHub.hs
=> Consider .tgz as .tar.gz

README.md, default.nix, nix/sources.nix, src/Niv/Cli.hs, src/Niv/Local/Cmd.hs, src/Niv/Sources.hs
=> Add niv add local for local sources

README.md, README.tpl.md
... and answer how to add a private repository.
CC @adrian-gierakowski
=> Add FAQ section to README

nix/sources.json
This updates niv itself to build with 20.03
=> Update to nixpkgs 20.03

CHANGELOG.md, README.md, package.yaml
Bumps the version and updates the changelog.
=> Release 0.2.14

src/Niv/Cli.hs, src/Niv/GitHub/Cmd.hs
Shows the nix-prefetch-url arguments and fix a misplaced colon.
=> Fix logging

README.md, README.tpl.md
Closes #252 
@antifuchs @Mic92 how does [this](https://github.com/nmattia/niv/blob/78780df4e3103358e6d6b58bc4b82c0f98047b93/README.md#how-do-i-import-a-subpath-of-a-source) look?
=> Add subpath handling to FAQ

src/Niv/Git/Test.hs, src/Niv/Update.hs
Some results were fetched _way_ too many times. All IO operations run in
updates are now cached. This makes `niv` effectively twice as fast.
*before:*
```
~/niv$ time niv add git git@github.com:nmattia/niv
Adding package niv
Writing new sources file
Done: Adding package niv
real    0m3.603s
user    0m0.079s
sys     0m0.031s
```
*after:*
```
~/niv$ time niv add git git@github.com:nmattia/niv
Adding package niv
Writing new sources file
Done: Adding package niv
real    0m1.387s
user    0m0.049s
sys     0m0.007s
```
=> Cache `Box` results

README.md, default.nix, src/Niv/Cli.hs
=> Show version with --version

src/Niv/Git/Cmd.hs
Whereas before niv would simply say that git didn't produce any output,
it now points out that the branch may not exist:
```
*Niv> :main add git git@github.com:nmattia/niv -b foobar
Adding package niv
FATAL: Could not read the output of 'git'.
command: git ls-remote git@github.com:nmattia/niv refs/heads/foobar
Git didn't produce any output. Does the branch 'foobar' exist?
FATAL: One or more packages failed to update:
niv: ExitFailure 1
ERROR: ExitFailure 1
*** Exception: ExitFailure 1
```
Closes #176
=> Clarify Git error on missing branch

README.md, src/Niv/Cli.hs, src/Niv/Logger.hs
=> Add flag for --no-colors

foo/default.nix
Fixes evaluation with newer Nixpkgs.
=> foo: stdenv.lib -> lib

README.md, README.tpl.md
- Update examples to recent version of nixpkgs
- Update obsolete sections following changes to niv
- Add information about the different ways of using niv sources
=> Update readme's documentation

default.nix, nix/sources.json, package.yaml, src/Niv/Cli.hs, src/Niv/Git/Cmd.hs, src/Niv/Git/Test.hs, src/Niv/GitHub/API.hs, src/Niv/GitHub/Cmd.hs, src/Niv/Local/Cmd.hs, src/Niv/Sources.hs, tests/git/default.nix
The actual Haskell-level code changes are simple enough, but I got stuck on adding overrides with never package versions for the Nix build because ormolu is packaged weirdly.
=> Work with (only) aeson 2.

README.md, README.tpl.md
=> Add motivation paragraph to 'Getting Started'

.github/workflows/test.yml
See <https://github.com/cachix/install-nix-action/issues/161>.
=> fix: Bump cachix install action

default.nix, foo/default.nix, nix/sources.nix, src/Niv/Sources.hs
Closes #362.
Only tested by running `nix-shell` after each commit.
Depends on #365 to unblock the pipeline.
=> refactor: statix recommendations

examples/cpp-libosmium/default.nix, examples/cpp-libosmium/nix/sources.json, examples/cpp-libosmium/nix/sources.nix, examples/cpp-libosmium/overlay/libosmium.nix
This bumps the nixpkgs version and sources.nix in the `cpp-libosmium` example.
=> Update cpp example
